experiment_name: 'beer_jan10'
data_name: 'beer_data'
N: 100
L: [None, 10, 50, 100]
training_iterations: 1
batch_size: 1
criterion: ['MSELoss', 'Hinge']
lr: 0.01
weight_decay: 1e-5
optimizer: 'SGD'
epochs: 1000
clip_grad: [.2, .5, 1]